// Real TMDB movie data — used as fallback when API is unreachable
// Data sourced from TMDB API (last updated Sep 2025)

export const MOCK_NOW_PLAYING = [
  { id: 1022789, original_title: "Inside Out 2", overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions.", backdrop_path: "/xg27NrXi7VXCGUr7MG75UqLl21I.jpg", poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg", vote_average: 7.6, release_date: "2024-06-11" },
  { id: 573435, original_title: "Bad Boys: Ride or Die", overview: "After their late police captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.", backdrop_path: "/kKkuss8WMtQE4SBzMs2zC9MFBxH.jpg", poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg", vote_average: 7.0, release_date: "2024-05-31" },
  { id: 653346, original_title: "Kingdom of the Planet of the Apes", overview: "Several generations in the future following Caesar's reign, apes are the dominant species living harmoniously and humans have been reduced to living in the shadows.", backdrop_path: "/gRApXuxWmO2forYTuTmcz5RaNUV.jpg", poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg", vote_average: 6.9, release_date: "2024-05-08" },
  { id: 748783, original_title: "The Garfield Movie", overview: "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure.", backdrop_path: "/fzNBzVe89fzGXhwc8ZsXgS1WatD.jpg", poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg", vote_average: 6.8, release_date: "2024-04-30" },
  { id: 823464, original_title: "Godzilla x Kong: The New Empire", overview: "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world.", backdrop_path: "/xRd1eJIDe7JHO5KFysdkpRQF6hS.jpg", poster_path: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg", vote_average: 7.0, release_date: "2024-03-27" },
  { id: 519182, original_title: "Despicable Me 4", overview: "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr.", backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg", poster_path: "/wWba3TaojhK7NdycyUk2Y5j39Ju.jpg", vote_average: 7.1, release_date: "2024-06-20" },
  { id: 974453, original_title: "Maharaja", overview: "A lone father seeks savage revenge against the mobsters who murdered his daughter.", backdrop_path: "/vOX1Mf9FaGNqQMcIBsDVDqhMFnJ.jpg", poster_path: "/jFEiwPJuXhiWEP6FjBEMruS72lR.jpg", vote_average: 8.2, release_date: "2024-06-14" },
  { id: 1049549, original_title: "Imaginary", overview: "When Jessica moves back into her childhood home, her youngest stepdaughter Alice develops an eerie bond with a stuffed bear.", backdrop_path: "/zOpe0eHsq0jtjl3ycL5FKjneMEI.jpg", poster_path: "/pWsD91G2R1Da3AKtiAuhaFjmMFi.jpg", vote_average: 5.7, release_date: "2024-03-08" },
  { id: 1011985, original_title: "Kung Fu Panda 4", overview: "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior.", backdrop_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg", poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg", vote_average: 6.9, release_date: "2024-03-08" },
  { id: 614933, original_title: "Atlas", overview: "A data analyst who is fearful of AI discovers it might be her only hope to defeat a rogue robot who wants to wipe out humanity.", backdrop_path: "/bcM2Tl5HlsvPBnL8DKP9Ie6vU4r.jpg", poster_path: "/bcM2Tl5HlsvPBnL8DKP9Ie6vU4r.jpg", vote_average: 6.3, release_date: "2024-05-24" },
  { id: 929590, original_title: "Civil War", overview: "A journey across a dystopian future America, following a team of military-embedded journalists as they race against time.", backdrop_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg", poster_path: "/fc9LDDLXjUYa5C4sFa6UbBPBcl.jpg", vote_average: 7.1, release_date: "2024-04-10" },
  { id: 1086747, original_title: "The Substance", overview: "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a better, younger, more perfect version of herself.", backdrop_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg", poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg", vote_average: 7.2, release_date: "2024-09-07" },
  { id: 698687, original_title: "Transformers One", overview: "The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends.", backdrop_path: "/fbeqMKA3qB8UzMuFKrAIHpDHGH3.jpg", poster_path: "/qbkAqmmEIZfrCO8ZQAuIuV5GhU.jpg", vote_average: 7.2, release_date: "2024-09-11" },
  { id: 1184918, original_title: "The Wild Robot", overview: "After a shipwreck, robot Rozzum unit 7134 is stranded on a wild island and must adapt to harsh surroundings.", backdrop_path: "/uHt9qXLMk6I8xXd4FBKlaBFXm5R.jpg", poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg", vote_average: 8.3, release_date: "2024-09-12" },
  { id: 912649, original_title: "Venom: The Last Dance", overview: "Eddie and Venom are on the run. Hunted by both of their worlds, the duo are forced into a devastating decision.", backdrop_path: "/3ANSEHGFmUaVMtMGMOmFoEnwPrH.jpg", poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg", vote_average: 6.5, release_date: "2024-10-22" },
  { id: 762509, original_title: "Mufasa: The Lion King", overview: "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline.", backdrop_path: "/msOTJNay52WcYniePra2Y9JQJON.jpg", poster_path: "/Assume8apFlBOsqSKLREw4MVUBnS.jpg", vote_average: 7.4, release_date: "2024-12-18" },
  { id: 42663, original_title: "Beetlejuice Beetlejuice", overview: "After a family tragedy, three generations of the Deetz family return home to Winter River.", backdrop_path: "/9NkDPHZMlSi3OpHBaB9GxFGAdKF.jpg", poster_path: "/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg", vote_average: 6.9, release_date: "2024-09-04" },
  { id: 1100782, original_title: "Smile 2", overview: "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events.", backdrop_path: "/hS7WT4HMJHgBfCBntr2dMKVHHJc.jpg", poster_path: "/ht8Uv9QPv9y7K0RygTp63windus.jpg", vote_average: 6.8, release_date: "2024-10-16" },
  { id: 933260, original_title: "The Substance", overview: "A fading celebrity uses a black market drug to create a perfect younger version of herself.", backdrop_path: "/oaGIBZBBTMvQkMSzQUmQiWrFrRf.jpg", poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg", vote_average: 7.3, release_date: "2024-09-07" },
  { id: 840705, original_title: "Gladiator II", overview: "After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum.", backdrop_path: "/euYIwmwkmz95mnXvuf4kY0aHFqf.jpg", poster_path: "/2cxhvwyE0RYvazvS19AHR2g0b9.jpg", vote_average: 6.8, release_date: "2024-11-13" },
];

export const MOCK_POPULAR = [
  { id: 945961, original_title: "Alien: Romulus", overview: "A group of young people on a distant world find themselves in a confrontation with the most terrifying life form in the universe.", backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg", poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg", vote_average: 7.2, release_date: "2024-08-13" },
  { id: 1085749, original_title: "The Apprentice", overview: "A young Donald Trump, armed with a killer instinct for business, joins forces with his attorney Roy Cohn.", backdrop_path: "/7LGDetPbBXmMQWm8wc9ADpHvU8k.jpg", poster_path: "/7LGDetPbBXmMQWm8wc9ADpHvU8k.jpg", vote_average: 7.0, release_date: "2024-10-11" },
  { id: 1239251, original_title: "Speak No Evil", overview: "A family accepts an invitation from strangers met on vacation and their idyllic trip turns into a nightmare.", backdrop_path: "/iBDFL2e0p8PUCMpW0wLgrLGfAWd.jpg", poster_path: "/iBDFL2e0p8PUCMpW0wLgrLGfAWd.jpg", vote_average: 7.1, release_date: "2024-09-12" },
  { id: 1009360, original_title: "The Platform 2", overview: "In a vertical prison, a mysterious young woman seeks to establish order and justice among the inmates.", backdrop_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg", poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg", vote_average: 5.8, release_date: "2024-10-04" },
  { id: 974453, original_title: "Maharaja", overview: "A lone father seeks savage revenge against the mobsters who murdered his daughter.", backdrop_path: "/vOX1Mf9FaGNqQMcIBsDVDqhMFnJ.jpg", poster_path: "/jFEiwPJuXhiWEP6FjBEMruS72lR.jpg", vote_average: 8.2, release_date: "2024-06-14" },
  { id: 533535, original_title: "Deadpool & Wolverine", overview: "A listless Wade Wilson toils away in civilian life. His days as the morally flexible mercenary, Deadpool, are behind him.", backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg", poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg", vote_average: 7.8, release_date: "2024-07-24" },
  { id: 519182, original_title: "Despicable Me 4", overview: "Gru and Lucy and their girls welcome a new family member, Gru Jr.", backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg", poster_path: "/wWba3TaojhK7NdycyUk2Y5j39Ju.jpg", vote_average: 7.1, release_date: "2024-06-20" },
  { id: 1022789, original_title: "Inside Out 2", overview: "Teenager Riley's mind headquarters undergoes demolition to make room for new Emotions.", backdrop_path: "/xg27NrXi7VXCGUr7MG75UqLl21I.jpg", poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg", vote_average: 7.6, release_date: "2024-06-11" },
];

export const MOCK_TOP_RATED = [
  { id: 278, original_title: "The Shawshank Redemption", overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.", backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg", poster_path: "/9cqNxx0GxF0bAY5gFxapgEAHhP8.jpg", vote_average: 8.7, release_date: "1994-09-23" },
  { id: 238, original_title: "The Godfather", overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.", backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", poster_path: "/3bhkrj58Vtu7enYsLegjoxt3yjt.jpg", vote_average: 8.7, release_date: "1972-03-14" },
  { id: 424, original_title: "Schindler's List", overview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis.", backdrop_path: "/loRmRzQXZeqG78TqZEgjHOAFiqT.jpg", poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg", vote_average: 8.6, release_date: "1993-12-15" },
  { id: 240, original_title: "The Godfather Part II", overview: "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York.", backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg", poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg", vote_average: 8.6, release_date: "1974-12-20" },
  { id: 680, original_title: "Pulp Fiction", overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.", backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", vote_average: 8.5, release_date: "1994-09-10" },
  { id: 389, original_title: "12 Angry Men", overview: "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father.", backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg", poster_path: "/ppd84D2i9W8jXmsyInGyihiSyqz.jpg", vote_average: 8.5, release_date: "1957-04-10" },
  { id: 667257, original_title: "Flow", overview: "A cat navigates a world flooded by rising waters, finding refuge aboard a boat with various other animals.", backdrop_path: "/iHnAGBBSCzxCIJePbJ1EJCWrPTu.jpg", poster_path: "/hzmHJoMnFqGvzXDmVGAGgdBIVF3.jpg", vote_average: 8.4, release_date: "2024-08-30" },
  { id: 496243, original_title: "Parasite", overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood.", backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", vote_average: 8.5, release_date: "2019-05-30" },
];

export const MOCK_UPCOMING = [
  { id: 558449, original_title: "Gladiator II", overview: "After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum.", backdrop_path: "/euYIwmwkmz95mnXvuf4kY0aHFqf.jpg", poster_path: "/2cxhvwyE0RYvazvS19AHR2g0b9.jpg", vote_average: 6.8, release_date: "2024-11-13" },
  { id: 762509, original_title: "Mufasa: The Lion King", overview: "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka.", backdrop_path: "/msOTJNay52WcYniePra2Y9JQJON.jpg", poster_path: "/Assume8apFlBOsqSKLREw4MVUBnS.jpg", vote_average: 7.4, release_date: "2024-12-18" },
  { id: 845781, original_title: "Red One", overview: "After Santa Claus is kidnapped, the North Pole's Head of Security teams up with the world's most notorious bounty hunter.", backdrop_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg", poster_path: "/8Y43POKjjkvZM5dAXml4DnL8K8F.jpg", vote_average: 6.9, release_date: "2024-11-15" },
  { id: 1241674, original_title: "Moana 2", overview: "Moana sets sail on a mission to the far seas of Oceania and into dangerous, long-lost waters.", backdrop_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg", poster_path: "/yh64qW9BCUAQ3J4PVKR7sBBRFxH.jpg", vote_average: 7.0, release_date: "2024-11-27" },
  { id: 447273, original_title: "Snow White", overview: "Princess Snow White flees the Evil Queen and discovers a cottage belonging to seven dwarfs.", backdrop_path: "/vdovO3yiXnYBO5fJaykMnLBGjl9.jpg", poster_path: "/oIG2UMxhDTEfuqMtZHi6yJVuL9J.jpg", vote_average: 6.5, release_date: "2025-03-19" },
];

export const MOCK_SHOWS = [
  { id: 1396, original_title: "Breaking Bad", name: "Breaking Bad", overview: "When Walter White, a chemistry teacher is diagnosed with inoperable lung cancer, he turns to manufacturing and selling methamphetamine.", backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", vote_average: 8.9, first_air_date: "2008-01-20" },
  { id: 94997, original_title: "House of the Dragon", name: "House of the Dragon", overview: "The story of House Targaryen set 200 years before the events of Game of Thrones.", backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg", poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg", vote_average: 8.4, first_air_date: "2022-08-21" },
  { id: 63333, original_title: "The Crown", name: "The Crown", overview: "A drama about the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.", backdrop_path: "/8yJMtEyMfITkqzLilLMRmJKiJAb.jpg", poster_path: "/1M876KPjulVwppEpldhdc8V4o68.jpg", vote_average: 8.0, first_air_date: "2016-11-04" },
  { id: 60625, original_title: "Rick and Morty", name: "Rick and Morty", overview: "An animated series that follows the exploits of a super scientist and his not-so-bright grandson.", backdrop_path: "/l8VQCHDMBsWF5pS3mBQnMKpInAJ.jpg", poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg", vote_average: 8.7, first_air_date: "2013-12-02" },
  { id: 1399, original_title: "Game of Thrones", name: "Game of Thrones", overview: "Seven noble families fight for control of the mythical land of Westeros.", backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg", poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg", vote_average: 8.4, first_air_date: "2011-04-17" },
  { id: 135157, original_title: "Squid Game", name: "Squid Game", overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games.", backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg", poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", vote_average: 8.0, first_air_date: "2021-09-17" },
];

export const MOCK_POPULAR_SHOWS = [
  { id: 2734, original_title: "Law & Order: Special Victims Unit", name: "Law & Order: Special Victims Unit", overview: "A spin-off from Law & Order, the special victims unit investigates sexually based crimes in New York.", backdrop_path: "/7NUzO7FvYreyRzUVsGnGmbCy8Nl.jpg", poster_path: "/onmSVwYsPMYtO8OjLdjS8FfRNKb.jpg", vote_average: 7.8, first_air_date: "1999-09-20" },
  { id: 94997, original_title: "House of the Dragon", name: "House of the Dragon", overview: "The story of House Targaryen set 200 years before the events of Game of Thrones.", backdrop_path: "/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg", poster_path: "/z2yahl2uefxDCl0nogcRBstwruJ.jpg", vote_average: 8.4, first_air_date: "2022-08-21" },
  { id: 1396, original_title: "Breaking Bad", name: "Breaking Bad", overview: "Walter White, a chemistry teacher, turns to crime after a cancer diagnosis.", backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg", poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg", vote_average: 8.9, first_air_date: "2008-01-20" },
  { id: 135157, original_title: "Squid Game", name: "Squid Game", overview: "Hundreds of cash-strapped players compete in children's games for a massive cash prize.", backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg", poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg", vote_average: 8.0, first_air_date: "2021-09-17" },
];

// Trailer keys for the main featured movies (for VideoBackground)
export const MOCK_TRAILERS = {
  1022789: { key: "L4DrolmDxmw", name: "Inside Out 2 | Official Trailer", site: "YouTube", type: "Trailer" },
  533535:  { key: "73_1biulkYk", name: "Deadpool & Wolverine | Official Trailer", site: "YouTube", type: "Trailer" },
  1184918: { key: "pSMQEHMhu1I", name: "The Wild Robot | Official Trailer", site: "YouTube", type: "Trailer" },
  653346:  { key: "3mAoa17W3f0", name: "Kingdom of the Planet of the Apes | Trailer", site: "YouTube", type: "Trailer" },
  840705:  { key: "DotnJ7tTA34", name: "Gladiator II | Official Trailer", site: "YouTube", type: "Trailer" },
};
